language: ruby
install: gem install asciidoctor
script: "./tools/convert.sh"
before_install:
  - openssl aes-256-cbc -K $encrypted_3a5998253966_key -iv $encrypted_3a5998253966_iv -in tools/id_rsa.enc -out tools/id_rsa -d
